project:
  type: book
  output-dir: docs

book:
  title: "Introduction to OMOP/OHDSI (in Thai 🇹🇭)"
  author: "Siriraj Informatics and Data Innovation Center (SiData+)"
  date: "8/21/2023"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - references.qmd

bibliography: references.bib

language: _language.yml

format:
  html:
    theme: cosmo

execute:
  freeze: auto

resources:
    - CNAME